/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package fractal;

import fractal.functions.madelbroth;
import java.awt.Button;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Convite
 */
public class Teste extends javax.swing.JPanel {
    FractalImage img = new FractalImage(3680, 2160, new madelbroth(256));
    /** Creates new form Teste */
    public Teste() {
        initComponents();
        JFrame window = new JFrame("Fractal Teste");
        
        JPanel p1 = new JPanel();
        p1.add(bt_save());
        p1.setBounds(0, 0, 200, 200);
        JPanel p2 = new JPanel();
        p2.add(img);
        p2.setBounds(200, 200, 300, 300);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setVisible(true);
        window.getContentPane().add(p1);
        window.getContentPane().add(p2);
        window.pack();
        window.setLocationRelativeTo(null);
        
    }
    private JButton bt_save(){
        JButton save = new JButton();
        save.setText("Salvar");
        return save;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1136, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public static void main(String[] args) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Teste();
            }

        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
